name: Maintenance - Nim 1.6.x

on:
  schedule:
    - cron: "0 0 1 2,8 *"
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version:
          - 1.6.20
          - 1.6.18
          - 1.6.16
          - 1.6.14
          - 1.6.12
          - 1.6.10
          - 1.6.8
          - 1.6.6
          - 1.6.4
          - 1.6.2
          - 1.6.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Platforms
        id: platforms
        run: |
          DOCKERFILE="./dockerfiles/${{ matrix.nim-version }}/Dockerfile"
          PLATFORMS="linux/amd64"

          if ! grep -q "URL_ARM64=none" "$DOCKERFILE"; then
            PLATFORMS="$PLATFORMS,linux/arm64"
          fi

          if ! grep -q "URL_ARMV7=none" "$DOCKERFILE"; then
            PLATFORMS="$PLATFORMS,linux/arm/v7"
          fi

          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/${{ matrix.nim-version }}
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          tags: nimlang/nim:${{ matrix.nim-version }}
