name: All versions

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim-version:
          - 2.2.2
          - 2.2.0
          - 2.0.14
          - 2.0.12
          - 2.0.10
          - 2.0.8
          - 2.0.6
          - 2.0.4
          - 2.0.2
          - 2.0.0
          - 1.6.20
          - 1.6.18
          - 1.6.16
          - 1.6.14
          - 1.6.12
          - 1.6.10
          - 1.6.8
          - 1.6.6
          - 1.6.4
          - 1.6.2
          - 1.6.0
          - 1.4.8
          - 1.4.6
          - 1.4.4
          - 1.4.2
          - 1.4.0
          - 1.2.12
          - 1.2.8
          - 1.2.6
          - 1.2.4
          - 1.2.2
          - 1.2.0
          - 1.0.10
          - 1.0.8
          - 1.0.6
          - 1.0.4
          - 1.0.2
          - 1.0.0
          - 0.20.2
          - 0.20.0
          - 0.19.6
          - 0.19.4
          - 0.19.2
          - 0.19.0
          - 0.18.9
          - 0.17.2
          - 0.17.0
          - 0.16.0
          - 0.15.2
          - 0.15.0
          - 0.14.3
          - 0.14.2
          - 0.14.0
          - 0.13.0

    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 2.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the builder-pusher app
        run: nimble build

      - name: Set up multiarch builder
        run: ./bin/nimage setup

      - name: Build and push the image
        run: ./bin/nimage build-and-push ${{ matrix.nim-version }}

