name: Build and Push the Docker Images for all Nim Versions to Docker Hub

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build_and_push:
    name: All Nim Versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: 2.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the builder-pusher app
        run: nimble build

      - name: Set up multiarch builder
        run: ./bin/nimage setup

      - name: Build and push the images
        run: ./bin/nimage build-and-push --all

