name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    name: Build and push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the builder-pusher app
        run: nimble build

      - name: Set up multiarch builder
        run: ./bin/nimage setup

      - name: Build and push images 
        run: ./bin/nimage build-and-push --all

